name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      artifact_path: ${{ steps.set-path.outputs.path }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect package.json
        id: detect
        run: |
          if [ -f package.json ]; then echo "has_pkg=true" >> $GITHUB_OUTPUT; else echo "has_pkg=false" >> $GITHUB_OUTPUT; fi

      - name: Install & Build (if package.json)
        if: steps.detect.outputs.has_pkg == 'true'
        run: |
          npm ci
          npm run build --if-present

      - name: Set artifact path
        id: set-path
        run: |
          if [ -d build ]; then echo "path=build" >> $GITHUB_OUTPUT
          elif [ -d dist ]; then echo "path=dist" >> $GITHUB_OUTPUT
          elif [ -d public ]; then echo "path=public" >> $GITHUB_OUTPUT
          elif [ -d docs ]; then echo "path=docs" >> $GITHUB_OUTPUT
          else echo "path=." >> $GITHUB_OUTPUT
          fi

  upload:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ needs.prepare.outputs.artifact_path }}

  deploy:
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
